DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS moderation_actions;
DROP TABLE IF EXISTS moderation_cases;
DROP TABLE IF EXISTS opportunity_recommendations;
DROP TABLE IF EXISTS applicant_contacts;
DROP TABLE IF EXISTS contact_requests;
DROP TABLE IF EXISTS application_status_history;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS favorite_employers;
DROP TABLE IF EXISTS favorite_opportunities;
DROP TABLE IF EXISTS employer_media_files;
DROP TABLE IF EXISTS opportunity_media_files;
DROP TABLE IF EXISTS opportunity_skill_requirements;
DROP TABLE IF EXISTS opportunity_tags;
DROP TABLE IF EXISTS opportunity_external_links;
DROP TABLE IF EXISTS opportunity_compensations;
DROP TABLE IF EXISTS opportunities;
DROP TABLE IF EXISTS employer_verification_documents;
DROP TABLE IF EXISTS employer_verification_reviews;
DROP TABLE IF EXISTS employer_verification_requests;
DROP TABLE IF EXISTS employer_external_links;
DROP TABLE IF EXISTS employer_memberships;
DROP TABLE IF EXISTS employers;
DROP TABLE IF EXISTS applicant_interest_tags;
DROP TABLE IF EXISTS applicant_skills;
DROP TABLE IF EXISTS applicant_projects;
DROP TABLE IF EXISTS applicant_external_links;
DROP TABLE IF EXISTS resume_versions;
DROP TABLE IF EXISTS resumes;
DROP TABLE IF EXISTS education_records;
DROP TABLE IF EXISTS applicant_privacy_settings;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS media_files;
DROP TABLE IF EXISTS email_verifications;

ALTER TABLE applicant_profiles DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE applicant_profiles DROP COLUMN IF EXISTS open_to_work;
ALTER TABLE applicant_profiles DROP COLUMN IF EXISTS primary_location_id;
ALTER TABLE applicant_profiles DROP COLUMN IF EXISTS about;
ALTER TABLE applicant_profiles DROP COLUMN IF EXISTS headline;

ALTER TABLE users DROP COLUMN IF EXISTS updated_by;
ALTER TABLE users DROP COLUMN IF EXISTS created_by;
ALTER TABLE users DROP COLUMN IF EXISTS deactivated_at;
ALTER TABLE users DROP COLUMN IF EXISTS blocked_at;
ALTER TABLE users DROP COLUMN IF EXISTS last_login_at;
ALTER TABLE users DROP COLUMN IF EXISTS email_verified_at;

DROP TYPE IF EXISTS media_owner_kind;
DROP TYPE IF EXISTS verification_document_type;
DROP TYPE IF EXISTS link_type;
DROP TYPE IF EXISTS tag_type;
DROP TYPE IF EXISTS privacy_visibility;
DROP TYPE IF EXISTS recommendation_status;
DROP TYPE IF EXISTS contact_request_status;
DROP TYPE IF EXISTS application_status;
DROP TYPE IF EXISTS salary_period;
DROP TYPE IF EXISTS opportunity_level;
DROP TYPE IF EXISTS employment_type;
DROP TYPE IF EXISTS work_format;
DROP TYPE IF EXISTS opportunity_status;
DROP TYPE IF EXISTS opportunity_type;
DROP TYPE IF EXISTS moderation_action_type;
DROP TYPE IF EXISTS moderation_target_type;
DROP TYPE IF EXISTS moderation_status;
DROP TYPE IF EXISTS membership_role;
DROP TYPE IF EXISTS employer_verification_status_v2;
DROP TYPE IF EXISTS employer_type;
DROP TYPE IF EXISTS email_verification_status;
DROP TYPE IF EXISTS email_verification_purpose;
